version: '3'
services:
  gnpsclassicalgroups-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gnpsclassicalgroups-dash
    volumes:
      - ./output:/app/output:rw
      - ./logs:/app/logs:rw
    ports:
    - "5848:5000"
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: classicalupset.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: classicalupset.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com
    deploy:
      resources:
        limits:
          memory: 2000M


networks:
  nginx-net:
    external:
      name: nginx-net